apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"  # Added quotes around the wildcard pattern for better readability and to avoid parsing issues

build:
  local:
    push: false
  artifacts:
    - image: cyoni/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"  # Added quotes around the wildcard pattern
            dest: .
