import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import axios from "axios";
import AuthProvider from "@/context/AuthProvider";
import App from "@/components/App";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getUser = async () => {
    try {
      const user = await axios.get(
        "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/users/current-user",
        {
          method: "get",
          headers: {
            Host: "ticketing.dev",
            Cookie: headers().get("cookie"),
          },
        }
      );

      console.log("got data", user.data);

      return user.data;
    } catch {
      return null;
    }
  };

  const user = await getUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider user={user}>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
