apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing
  template:
    metadata:
      labels:
        app: ticketing
    spec:
      containers:
        - name: ticketing
          image: cyoni/ticketing-service
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-srv
spec:
  selector:
    app: ticketing
  ports:
    - name: ticketing
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP # Allows access only within the cluster
